# Generated by Django 3.1.7 on 2021-05-16 18:28

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
        ),
        migrations.CreateModel(
            name='SendSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_tittle', models.CharField(max_length=500, verbose_name='İçerik')),
                ('support_name', models.CharField(max_length=50, verbose_name='İsim Soyisim')),
                ('support_email', models.EmailField(max_length=50, verbose_name='Mail Adresi')),
                ('support_phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('support_content', models.CharField(max_length=50, verbose_name='Başlık')),
                ('support_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-support_date'],
            },
        ),
        migrations.CreateModel(
            name='ShowArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('article_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekleyin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.category', verbose_name='Kategori')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AddComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.showarticle', verbose_name='Makale')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yorum Yapan')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
