# Generated by Django 3.2.4 on 2021-10-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_name', models.CharField(max_length=50, verbose_name='İsim Soyisim')),
                ('support_email', models.EmailField(max_length=50, verbose_name='Mail Adresi')),
                ('support_phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('support_content', models.CharField(max_length=50, verbose_name='Başlık')),
                ('support_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-support_date'],
            },
        ),
    ]
