# Generated by Django 3.2.4 on 2021-10-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Kullanıcı Adı')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='E-posta')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Son Oturum')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
